### ISSUE TITLE
No LICENCE

### ISSUE THREAD

**Issue by flungo** [frioux/offlineimap#1]
Could this project please be licensed? I am preferably looking for something similar to MIT / Apache 2 or even Public Domain

**Comment by frioux** [comment]
Yeah sure, I'll add a license tonight.  Don't forget though that the actual software inside (offlineimap, etc) each has it's own license.

**Comment by flungo** [comment]
Thanks, that would be great. Will be using a fork of this as a submodule in a helper script.

Interesting point, does something that aids the install of another piece of code need to respect the license of the code it installs (with respects to using a license compatible for the inclusion/use of that application). GNU GPL2 which OfflineIMAP is licensed under wouldn't be a disaster for me, I just have a preference for less restrictive licensing on small projects.

**Comment by frioux** [comment]
I have no idea about the interaction between licenses at that level.  If you find anything about it I'd be interested in what you find though!

**Comment by frioux** [comment]
See latest commit

**Comment by flungo** [comment]
Wonderful, thanks.
